spring:
  application:
    name: ad-data-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
facebook:
  app-id: 1426714058447826
  app-secret: ed9299bca204b2722bebfc27c9b79aa8
  access-token: EAAURlsCmW9IBPGVu0hDYRZB1SCZCP8F2KEdoFg7ZB2iLoH2IIqEreZBLUaL0qI0bRVKyj0geC1CeDZC3AfyrHWPX1kq4ZBTZBBTFm2fBzaSvg67b9zGSDxPxeFT7NAV3vIn8uxl42KK9WXdn7K01vpO0k2oaNg5pdcZASOy40pqypebbRG9v3CvAY93ZAaxJuM2qSa7CcXDLH